### ISSUE TITLE
jax_utils.prefetch_to_device failed with CUDA_ERROR_INVALID_HANDLE

### ISSUE THREAD

**Issue by BoyuanJackChen** [google/flax#432] opened 2020-08-28 05:00 UTC
I am trying to place a tensorflow iterator on GPU with jax_utils.prefetch_to_device, as shown in the imagenet example (https://github.com/google/flax/blob/master/examples/imagenet/train.py). 

I converted a numpy array to tensorflow dataset, mapped with numpy convertion, and then called prefetch_to_device. 
```
target_data = tf.data.Dataset.from_tensor_slices(target_batched)
target_data = map(prepare_tf_data, target_data)
target_iter = jax_utils.prefetch_to_device(iter(target_data), 2, devices=[xla_bridge.devices()[0]])
...
for target_batch in target_iter:
    ...
```
Unfortunately, I received the error below. And I wonder if it is fixable. 
```
2020-08-27 20:46:14.319662: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_client.cc:1708] Execution of replica 0 failed: Internal: Failed to launch CUDA kernel: CUDA_ERROR_INVALID_HANDLE: invalid resource handle
Traceback (most recent call last):
  File "batchify_tf.py", line 657, in <module>
    result_dir=result_dir, step_report=step_report)
  File "batchify_tf.py", line 540, in train_nerf_cnf
    (loss, (rgb_c, rgb_f)), (grad_c_batch, grad_f_batch) = grad_fn(optimizer_c.target, optimizer_f.target)
  File "/raid/anaconda3_2020/lib/python3.7/site-packages/jax/api.py", line 489, in value_and_grad_f
    ans, vjp_py, aux = _vjp(f_partial, *dyn_args, has_aux=True)
  File "/raid/anaconda3_2020/lib/python3.7/site-packages/jax/api.py", line 1520, in _vjp
    out_primal, out_vjp, aux = ad.vjp(flat_fun, primals_flat, has_aux=True)
  File "/raid/anaconda3_2020/lib/python3.7/site-packages/jax/interpreters/ad.py", line 112, in vjp
    out_primals, pvals, jaxpr, consts, aux = linearize(traceable, *primals, has_aux=True)
  File "/raid/anaconda3_2020/lib/python3.7/site-packages/jax/interpreters/ad.py", line 97, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
  File "/raid/anaconda3_2020/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 423, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/raid/anaconda3_2020/lib/python3.7/site-packages/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "batchify_tf.py", line 534, in loss_fn
    coarse=coarse, fine=fine, rand=True)
  File "batchify_tf.py", line 187, in render_rays_cnf
    z_vals = jnp.linspace(near, far, coarse)
  File "/raid/anaconda3_2020/lib/python3.7/site-packages/jax/numpy/lax_numpy.py", line 2423, in linspace
    delta = lax.convert_element_type(stop - start, computation_dtype) / div
  File "/raid/anaconda3_2020/lib/python3.7/site-packages/jax/numpy/lax_numpy.py", line 4384, in deferring_binary_op
    return binary_op(self, other)
  File "/raid/anaconda3_2020/lib/python3.7/site-packages/jax/numpy/lax_numpy.py", line 357, in <lambda>
    fn = lambda x1, x2: lax_fn(*_promote_args(numpy_fn.__name__, x1, x2))
  File "/raid/anaconda3_2020/lib/python3.7/site-packages/jax/lax/lax.py", line 304, in sub
    return sub_p.bind(x, y)
  File "/raid/anaconda3_2020/lib/python3.7/site-packages/jax/core.py", line 276, in bind
    return self.impl(*args, **kwargs)
  File "/raid/anaconda3_2020/lib/python3.7/site-packages/jax/interpreters/xla.py", line 225, in apply_primitive
    return compiled_fun(*args)
  File "/raid/anaconda3_2020/lib/python3.7/site-packages/jax/interpreters/xla.py", line 330, in _execute_compiled_primitive
    out_bufs = compiled.execute(input_bufs)
RuntimeError: Internal: Failed to launch CUDA kernel: CUDA_ERROR_INVALID_HANDLE: invalid resource handle
```

**Comment by avital** [comment] 2020-08-28 09:24
@hawkinsp @levskaya @jheek, do one of you know on the top of your head what might be causing this error?

**Comment by andsteing** [comment] 2020-09-16 13:38
Sometimes Tensorflow allocates memory on GPU and that can result in cryptic error messages. Did you try the following?

```python
tf.config.experimental.set_visible_devices([], "GPU")
```

**Comment by avital** [comment] 2020-09-24 15:46
Hi @BoyuanJackChen -- sorry for the late request but can you explain how we could reproduce this? (ideally in a GitHub repo we can clone and run directly), as well as a description of which hardware you're using, and which versions of TF, JAX, jaxlib you have installed?

We haven't seen that error ourselves, as far as I know.

**Comment by avital** [comment] 2020-09-24 15:52
cc @mohitreddy1996

**Comment by avital** [comment] 2020-12-12 18:59
Hi @BoyuanJackChen -- I'll close this issue for now since it's been a while. If you can share more details on how to reproduce this issue, we're happy to take a look.

**Closed by avital** 2020-12-12 18:59 UTC
Labels: Status: pending
