### ISSUE TITLE
Add a Flax guided tour

### ISSUE THREAD

**Issue by BertrandRdp** [google/flax#523] opened 2020-10-09 12:27 UTC
We want to add a guided tour of Flax, walking users through a real world workflow:
- [x] JAX basics
- [x] Core module abstraction
- [x] Storing and inspecting data
- [x] Different types of parameters
- [ ] More complicated layers like transformers
- [ ] Model and performance inspection
- [x] Creating your own layers

**Comment by andsteing** [comment] 2020-10-23 14:27
For reference : the current guided tour has the following structure (in a single notebook):

1.  JAX intro : mostly links to JAX documentation and tutorials
2.  NN in JAX without Flax : init/apply in two separate functions
3.  Flax modules : starting with an example of `Dense` and then going into more details:
    - composition
    - parameter sharing
    - shape inference
    - `Model`
    - state
4.  Optimizer : plots of sampled 2d dots, then approximating with linear regression, and then with momentum optimizer
5.  Serialization : converting objects to dictionaries of arrays, serializing with messagepack
6.  Advanced features
    - `MultiOptimizer`
    - Multiple methods
    - Transforming sub module parameters.

**Comment by marcvanzee** [comment] 2022-02-03 15:56
I'm closing this issue since I think the guided tour is actually in a great state. For the two remaining points:

- Model inspection:  see the [Model surgery HOWTO](https://flax.readthedocs.io/en/latest/howtos/model_surgery.html)
- More complicated layers: I am not sure if this is necessary for the guided tour. We can add those as HOWTOs if necessary, but right now I don't see a real need, I guess if someone would like to understand a Transformer they can read one of the many great "Annotated Transformer" tutorials.

**Closed by marcvanzee** 2022-02-03 15:56 UTC
Labels: Status: in progress, Priority: P1 - high
