### ISSUE TITLE
Reading incorrect memory on TPU (ft. `flax.linen.transforms.scan`)

### ISSUE THREAD

**Issue by sjmielke** [google/flax#769] opened 2020-12-28 23:28 UTC
### Problem you have encountered:

Simple RNNLM-esque example (based on distributed seq2seq example) seems to read wrong/unallocated memory, resulting in nondeterminism on Google Colab TPUs. Using `flax.linen.transforms.scan` and `jax.value_and_grad`, both seem necessary to get this behavior, as is the sketchy looking use of multiple LSTM cells after one another (`LMCell.__call__`)...

### What you expected to happen:

I defined a function that looks determinstic, triggered no errors or warnings, and acts "properly" on CPU and GPU, wrapped it in `jax.value_and_grad` (full code in notebook):
```python
class LMCell(nn.Module):
    @functools.partial(
        nn.transforms.scan,
        length=SEQUENCE_LENGTH-1,
        variable_broadcast='params',
        split_rngs={'params': False},
    )
    @nn.compact
    def __call__(self, lstm_states):
        inputs = self.param('stuff', nn.initializers.zeros, VOCAB_SIZE)
        new_lstm_states = []
        for lstm_state, lstm in zip(lstm_states, [nn.LSTMCell() for _ in range(3)]):
            new_lstm_state, inputs = lstm(lstm_state, inputs)
            new_lstm_states.append(new_lstm_state)
        logits = inputs
        return new_lstm_states, logits

class LM(nn.Module):
    @nn.compact
    def __call__(self):
        lstm_states = [(jnp.zeros(HIDDEN_SIZE, jnp.float32),) * 2] * 3
        _, logits = LMCell()(lstm_states)
        return -jnp.sum(logits)

params = LM().init(
    {'params': jax.random.PRNGKey(0)},
)['params']

@jax.value_and_grad
def f(params):
    return LM().apply(
        {'params': params},
        rngs={'lstm': jax.random.PRNGKey(0)},
    )
```
I now would expect this snippet should print the same value twice:
```python
print(f(params)[0])
x = jnp.log(-jnp.ones((20000, 20000)))
print(f(params)[0])
```
...but on TPUs we get `0.0` and `nan` in the linked Colab.

(Also, as a bonus, trying to remove the kind of useless intermediary module (`LM`) makes the code shorter and simpler... but also sometimes doesn't seem to terminate? And if it does yields different but still non-deterministic results? Didn't try to isolate or analyze this one much though, so feel free to ignore.)

### Logs, error messages, etc:

None.

### Steps to reproduce:

https://colab.research.google.com/drive/18Tcz0gQp7Eride_cFbw09FNDFPVIoScv?usp=sharing
(works the same on stable and master)

**Comment by avital** [comment] 2020-12-29 15:03
Hello and welcome @sjmielke! Wow, this is an odd issue, let me ask some folks that know more about JAX and TPUs to see if can start teasing this apart. A bunch of folks are on vacation now, so perhaps it will take a bit of time.

Have you been able to find any workaround? Or are you using GPUs for now?

**Comment by avital** [comment] 2020-12-29 15:09
I tinkered with your Colab and by adding `jax.jit` outside of `jax.value_and_grad`, it seems to work. (I changed `__call__` to use `jnp.ones` so that I see a non-zero value). Not the most satisfying answer, but please let me know if this unblocks you.

**Comment by sjmielke** [comment] 2020-12-29 15:14
Interesting... First of all I should've said I'm not in a hurry at all---there's plenty other stuff to be done for this project, I probably got some old pretrained RNNLMs lying around I can just swap in and even if not GPUs are indeed just fine for training the little LM I need---but thanks for the quick take up!

My predominant worry with this issue is that this looks like I did something I "wasn't supposed to" that isn't prohibited and warned about; in particular the three LSTMs seem very sketchy cause... What are the dimensions in the middle? Aren't they un(der)defined?

**Comment by avital** [comment] 2020-12-29 15:26
Nothing seems obviously wrong to me in your code, though I've never personally trained an LSTM! I'm assuming you plan to actually pipe through inputs to your layers (now you seem to be defining the inputs as parameters inside of them?)

All built-in modules use shape inference. In this case, `LSTMCell` deduces its output parameter shapes based on the last dimension of the hidden state passed in, and the input parameter shapes are deduced by shape inference in `Dense` based on the last dimension of the input passed in.

(You can always define modules with explicit `in_features` and avoid using `nn.compact` altogether, which would be pretty similar to PyTorch. But many of our users find that tedious, and we're happy to "own" the complexity in the library to avoid requiring specifying input dimensions, and allowing using flow control like conditionals and loops in forward pass functions, like in your example.)

**Comment by sjmielke** [comment] 2020-12-29 15:59
Yeah, the original code had a bunch more complexity and was vmapping and all of that fun, I tried to reduce as much as possible, hence the nonsensical setup ;)

And of course, the hidden states! I had completely forgotten, those *do* determine things! Nice! Thanks!

**Comment by jheek** [comment] 2021-01-06 15:50
Looks like an XLA TPU bug to me.
A pretty strange one though. I can reproduce it only with the number of LSTM stacks being >= 3. 
Using jit seems like a sensible workaround but it is good to report this bug with the repro to JAX as well so they can take a closer look at the miscompilation (or autograd bug but that seems unlikely to me).


>> My predominant worry with this issue is that this looks like I did something I "wasn't supposed to" that isn't prohibited and warned about; in particular the three LSTMs seem very sketchy cause... What are the dimensions in the middle? Aren't they un(der)defined?

LSTMs are a little funny because the output features can be inferred from the carry shape unlike Dense or Conv where we can only infer the input features from the input arguments.

**Comment by avital** [comment] 2021-01-06 16:07
@blakehechtman suggested that it may be a silent TPU OOM bug that isn't captured correctly. @jheek 's point about it not reproducing with smaller nets may suggest this as well. Probably the 20000x20000 array, the negative and the log are filling up device memory (1.5GB each)

**Comment by avital** [comment] 2021-01-11 22:27
I'll close this since JAX is the right place to discuss this, and there's a workaround for now. (https://github.com/google/jax/issues/5355). Thanks @sjmielke for reporting!

**Closed by avital** 2021-01-11 22:27 UTC
Labels: Priority: P3 - low, Status: accepted
