### ISSUE TITLE
Extend examples/imagenet/ with illustration of fine-tuning

### ISSUE THREAD

**Issue by andsteing** [google/flax#1065] opened 2021-03-01 19:50 UTC
Something along the lines : download pretrained resnet, replace head with a new initialized head, train first head, then whole network.

This would illustrate some model surgery & multi optimizer.

**Comment by andsteing** [comment] 2021-03-01 19:50
See also related issue #1022

**Comment by marcvanzee** [comment] 2021-03-12 13:54
Nice idea! Maybe we can consider doing a HOWTO and marge this issue with #789?

**Comment by marcvanzee** [comment] 2022-05-12 07:51
This seems to be duplicate of #1567.

**Closed by marcvanzee** 2022-05-12 07:51 UTC
Labels: Priority: P2 - eventual
