### ISSUE TITLE
RNN Layers

### ISSUE THREAD

**Issue by kamalkraj** [google/flax#1677] opened 2021-11-23 09:02 UTC
### Description of the model to be implemented
Is there a plan to add a simple RNN cell and a Layer wrapper that can take an RNN Cell, output an RNN Layer like in TensorFlow

### Reference implementations in other frameworks
https://www.tensorflow.org/api_docs/python/tf/keras/layers/RNN

I am interested in contributing this feature

**Comment by cgarciae** [comment] 2021-11-27 04:06
Interested in this topic as well.

**Comment by jheek** [comment] 2021-11-29 16:06
There's nothing concrete on the roadmap right now. I think such an abstraction could be helpful and pretty lightweight in Flax as well. Do you want to make a proposal?

**Comment by kamalkraj** [comment] 2021-11-29 19:21
Sure @jheek.

**Comment by marcvanzee** [comment] 2022-09-06 13:29
Assigning this to @cgarciae since he proposed the RNN Flip in #2396

**Comment by marcvanzee** [comment] 2022-09-06 13:45
Duplicate of #2170

**Closed by marcvanzee** 2022-09-06 13:45 UTC
Labels: Priority: P2 - eventual
