### ISSUE TITLE
Remat decorator doesn't save memory under JIT compiled functions

### ISSUE THREAD

**Issue by igrekun** [google/flax#1285] opened 2021-04-29 11:09 UTC
### Problem you have encountered:

@nn.remat decorator doesn't save memory under JIT compiled functions.

### What you expected to happen:

Expected compiled and vanilla functions to complete successfully.

### Logs, error messages, etc:

OOM on TPU device when JIT compiled version is executed.

### Steps to reproduce:
https://colab.research.google.com/drive/1_XbQ_oq8APHmlJT-1oo_tU4CwCHj4BNZ?usp=sharing

**Comment by jheek** [comment] 2021-04-29 12:20
I reproduced the problem. Adding remat increases memory from 8Gb -> 11Gb.
I rewrote it to use jax.remat directly and the problem persists.
So my guess is something in JAX or XLA is going wrong. I'll investigate some more

**Comment by igrekun** [comment] 2021-04-29 12:29
Must be JAX or XLA, since I got OOM reimplementing the test in Haiku too. Most likely it's not the wrapper problem.
In case Haiku team needs the test case it is below

https://colab.research.google.com/drive/1V6vR64PYeuh1dFLOZ0VM3jJwMwq292Bw?usp=sharing

**Comment by jheek** [comment] 2021-04-29 13:10
The problem doesn't reproduce on a normal TPU machine (non-colab) either. Actually on a normal TPU the model without remat uses 2x less memory and the remat version 10x less.

I'll close this for now because this is clearly not Flax related but some problem in JAX/XLA. Please open an issue on the JAX repo

**Closed by jheek** 2021-04-29 13:10 UTC
