### ISSUE TITLE
Issue with mkdocstrings since recent changes on struct.dataclass

### ISSUE THREAD

**Issue by felixchalumeau** [google/flax#2648] opened 2022-11-22 18:24 UTC
Hi :wave: 

I just wanted to notify that the [recent PR about `struct.dataclass`](https://github.com/google/flax/pull/2505) has an impact on auto-docstrings generation of classes that inherits from PyTreeNode.

### System information
- Linux Ubuntu 18.04:
- Flax version: 0.6.2 (and 0.3.15<=jax, jaxlib<=0.3.25)
- Python version: 3.8.15

### Problem you have encountered:
Recently, our documentation started failing, and its due to the move from flax 0.6.1 to flax 0.6.2; in particular, it seems (very likely to be) related to the PR #2505 .

Our project [QDax](https://github.com/adaptive-intelligent-robotics/QDax) has two classes that inherit from PyTreeNode and our documentation now fails because of the auto-docstrings parsing made of one those (the other would also probably make it fail but it just not called before the fail occurs).

The error message is related below.

Is it something that you desired on your side or is it an unwanted side effect? Any advice on a cleaner fix than just avoiding version 0.6.2?

Thanks!

### Logs, error messages, etc:

Here is the Error (EmitterState is the name of the class that inherits from PyTreeNode):

```
WARNING  -  mkdocstrings_handlers: qdax.core.emitters.emitter.EmitterState: No type annotation for parameter 'PyTreeNode'
ERROR    -  mkdocstrings: 'docstring'
            Traceback (most recent call last):
              File "/home/felix/.local/lib/python3.8/site-packages/pytkdocs/cli.py", line 205, in main
                output = json.dumps(process_json(line))
              File "/home/felix/.local/lib/python3.8/site-packages/pytkdocs/cli.py", line 114, in process_json
                return process_config(json.loads(json_input))
              File "/home/felix/.local/lib/python3.8/site-packages/pytkdocs/cli.py", line 91, in process_config
                obj = loader.get_object_documentation(path, members)
              File "/home/felix/.local/lib/python3.8/site-packages/pytkdocs/loader.py", line 358, in get_object_documentation
                root_object = self.get_module_documentation(leaf, members)
              File "/home/felix/.local/lib/python3.8/site-packages/pytkdocs/loader.py", line 436, in get_module_documentation
                root_object.add_child(self.get_module_documentation(leaf))
              File "/home/felix/.local/lib/python3.8/site-packages/pytkdocs/loader.py", line 436, in get_module_documentation
                root_object.add_child(self.get_module_documentation(leaf))
              File "/home/felix/.local/lib/python3.8/site-packages/pytkdocs/loader.py", line 426, in get_module_documentation
                root_object.add_child(self.get_class_documentation(child_node))
              File "/home/felix/.local/lib/python3.8/site-packages/pytkdocs/loader.py", line 544, in get_class_documentation
                self.add_fields(
              File "/home/felix/.local/lib/python3.8/site-packages/pytkdocs/loader.py", line 612, in add_fields
                root_object.add_child(add_method(child_node))
              File "/home/felix/.local/lib/python3.8/site-packages/pytkdocs/loader.py", line 809, in get_annotated_dataclass_field
                docstring=attribute_data["docstring"],
            KeyError: 'docstring'

```

### Steps to reproduce:
Check this docs CI https://readthedocs.org/projects/qdax/builds/18708245/

**Comment by marcvanzee** [comment] 2022-11-23 11:59
Assigning this to @cgarciae who merged the original PR.

**Comment by marcvanzee** [comment] 2022-11-23 12:00
And apologies for breaking your documentation @felixchalumeau! We'll try fixing this soon.

**Comment by cgarciae** [comment] 2022-11-23 12:13
Will take a look! Another possible culprit is #2468 that recently refactored the dataclass definition process.

**Comment by cgarciae** [comment] 2022-11-23 19:55
Hey @felixchalumeau, I created a very simple project but could not reproduce the error with the current `main` branch:

```python
# test_proj/__init__.py

from flax.struct import PyTreeNode

class TestPytree(PyTreeNode):
    """A simple pytree node for testing purposes."""

    a: int
    """A intenger field."""
    b: str
    """A string field."""

    def test_method(self, x: int) -> int:
        return self.a + x
```
```markdown
<!-- docs/index.md -->

::: test_proj.TestPytree
    options:
      members:
        - a
        - b
        - test_method
```
```yaml
# mkdocs.yml

site_name: My Docs

theme:
  name: "material"

plugins:
- search
- mkdocstrings
```
**Result**
![Screenshot 2022-11-23 at 14-50-48 My Docs](https://user-images.githubusercontent.com/5862228/203634618-b5863593-ec05-49b2-ab35-9426c589d269.png)

Can you try to get a minimal repro? Maybe I am missing something.

**Comment by marcvanzee** [comment] 2022-12-13 07:45
@felixchalumeau friendly ping: could you please provide a minimal repro?

**Closed** 2023-03-30 16:22 UTC
Labels: Priority: P3 - no schedule
