### ISSUE TITLE
 \examples\imagenet\models_test.py fails on GPU (8 x Titan-m):

### ISSUE THREAD

**Issue by mattiasmar** [google/flax#1731] opened 2021-12-16 14:06 UTC
### Problem you have encountered:
Running [flax\examples\imagenet\models_test.py](examples/imagenet/models_test.py)  hits runtime error.

### What you expected to happen:
Test to exit with OK status.

### Logs, error messages, etc:

Log trace says:
```
RuntimeError: UNKNOWN: device kernel image is invalid
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_asm_compiler.cc(69): 'cuLinkComplete(link_state, &cubin_out, &cubin_size)'
```

**Full log trace:**

```
/usr/bin/python3 -u /workdisk/jax/FlaxExamples/flax/examples/imagenet/models_test.py
Running tests under Python 3.8.10: /usr/bin/python3
[ RUN      ] ResNetV1Test.test_resnet_v1_model
I1216 13:56:24.360462 140268445701952 xla_bridge.py:243] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
I1216 13:56:25.496197 140268445701952 xla_bridge.py:243] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
2021-12-16 13:56:25.729863: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:419] ********************************************************************************
2021-12-16 13:56:25.729899: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:420] The XLA GPU backend doesn't support unoptimized code generation but 
2021-12-16 13:56:25.729910: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:422] --xla_backend_optimization_level is set to 0!
2021-12-16 13:56:25.729917: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:424] (Supported configuration is --xla_backend_optimization_level >= 2.)
2021-12-16 13:56:25.729923: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:426] ********************************************************************************
2021-12-16 13:56:25.791850: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:419] ********************************************************************************
2021-12-16 13:56:25.791876: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:420] The XLA GPU backend doesn't support unoptimized code generation but 
2021-12-16 13:56:25.791903: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:422] --xla_backend_optimization_level is set to 0!
2021-12-16 13:56:25.791909: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:424] (Supported configuration is --xla_backend_optimization_level >= 2.)
2021-12-16 13:56:25.791933: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:426] ********************************************************************************
2021-12-16 13:56:25.852572: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:419] ********************************************************************************
2021-12-16 13:56:25.852607: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:420] The XLA GPU backend doesn't support unoptimized code generation but 
2021-12-16 13:56:25.852634: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:422] --xla_backend_optimization_level is set to 0!
2021-12-16 13:56:25.852642: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:424] (Supported configuration is --xla_backend_optimization_level >= 2.)
2021-12-16 13:56:25.852649: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:426] ********************************************************************************
2021-12-16 13:56:25.904518: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:419] ********************************************************************************
2021-12-16 13:56:25.904543: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:420] The XLA GPU backend doesn't support unoptimized code generation but 
2021-12-16 13:56:25.904551: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:422] --xla_backend_optimization_level is set to 0!
2021-12-16 13:56:25.904557: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:424] (Supported configuration is --xla_backend_optimization_level >= 2.)
2021-12-16 13:56:25.904562: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:426] ********************************************************************************
2021-12-16 13:56:25.956814: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:419] ********************************************************************************
2021-12-16 13:56:25.956839: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:420] The XLA GPU backend doesn't support unoptimized code generation but 
2021-12-16 13:56:25.956865: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:422] --xla_backend_optimization_level is set to 0!
2021-12-16 13:56:25.956874: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:424] (Supported configuration is --xla_backend_optimization_level >= 2.)
2021-12-16 13:56:25.956889: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:426] ********************************************************************************
2021-12-16 13:56:26.025412: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:419] ********************************************************************************
2021-12-16 13:56:26.025437: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:420] The XLA GPU backend doesn't support unoptimized code generation but 
2021-12-16 13:56:26.025446: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:422] --xla_backend_optimization_level is set to 0!
2021-12-16 13:56:26.025451: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:424] (Supported configuration is --xla_backend_optimization_level >= 2.)
2021-12-16 13:56:26.025456: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:426] ********************************************************************************
2021-12-16 13:56:26.025946: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:419] ********************************************************************************
2021-12-16 13:56:26.025996: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:420] The XLA GPU backend doesn't support unoptimized code generation but 
2021-12-16 13:56:26.026010: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:422] --xla_backend_optimization_level is set to 0!
2021-12-16 13:56:26.026021: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:424] (Supported configuration is --xla_backend_optimization_level >= 2.)
2021-12-16 13:56:26.026031: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:426] ********************************************************************************
2021-12-16 13:56:26.026043: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:419] ********************************************************************************
2021-12-16 13:56:26.026077: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:419] ********************************************************************************
2021-12-16 13:56:26.026110: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:420] The XLA GPU backend doesn't support unoptimized code generation but 
2021-12-16 13:56:26.026127: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:422] --xla_backend_optimization_level is set to 0!
2021-12-16 13:56:26.026140: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:424] (Supported configuration is --xla_backend_optimization_level >= 2.)
2021-12-16 13:56:26.026151: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:426] ********************************************************************************
2021-12-16 13:56:26.026163: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:420] The XLA GPU backend doesn't support unoptimized code generation but 
2021-12-16 13:56:26.026176: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:422] --xla_backend_optimization_level is set to 0!
2021-12-16 13:56:26.026184: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:424] (Supported configuration is --xla_backend_optimization_level >= 2.)
2021-12-16 13:56:26.026191: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:426] ********************************************************************************
2021-12-16 13:56:26.079888: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:1099] The CUDA linking API did not work. Please use XLA_FLAGS=--xla_gpu_force_compilation_parallelism=1 to bypass it, but expect to get longer compilation time due to the lack of multi-threading.
[  FAILED  ] ResNetV1Test.test_resnet_v1_model
======================================================================
ERROR: test_resnet_v1_model (__main__.ResNetV1Test)
ResNetV1Test.test_resnet_v1_model
Tests ResNet V1 model definition and output (variables).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workdisk/jax/FlaxExamples/flax/examples/imagenet/models_test.py", line 46, in <module>
    absltest.main()
  File "/usr/local/lib/python3.8/dist-packages/absl/testing/absltest.py", line 2007, in main
    _run_in_app(run_tests, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/absl/testing/absltest.py", line 2124, in _run_in_app
    app.run(main=main_function)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.8/dist-packages/absl/testing/absltest.py", line 2122, in main_function
    function(argv, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/absl/testing/absltest.py", line 2438, in run_tests
    result = _run_and_get_tests_result(
  File "/usr/local/lib/python3.8/dist-packages/absl/testing/absltest.py", line 2409, in _run_and_get_tests_result
    test_program = unittest.TestProgram(*args, **kwargs)
  File "/usr/lib/python3.8/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/usr/lib/python3.8/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/local/lib/python3.8/dist-packages/absl/testing/_pretty_print_reporter.py", line 87, in run
    return super(TextTestRunner, self).run(test)
  File "/usr/lib/python3.8/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.8/unittest/case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/workdisk/jax/FlaxExamples/flax/examples/imagenet/models_test.py", line 35, in test_resnet_v1_model
    variables = model_def.init(
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 1138, in init
    _, v_out = self.init_with_output(
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 1107, in init_with_output
    return self.apply(
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 1074, in apply
    return apply(
  File "/usr/local/lib/python3.8/dist-packages/flax/core/scope.py", line 730, in wrapper
    y = fn(root, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 1329, in scope_fn
    return fn(module.clone(parent=scope), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/transforms.py", line 883, in wrapped_fn
    return prewrapped_fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 333, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 618, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/workdisk/jax/FlaxExamples/flax/examples/imagenet/models.py", line 100, in __call__
    x = conv(self.num_filters, (7, 7), (2, 2),
  File "<string>", line 17, in __init__
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 719, in __post_init__
    object.__setattr__(self, 'scope', self.parent.scope.push(self.name))
  File "/usr/local/lib/python3.8/dist-packages/flax/core/scope.py", line 459, in push
    rngs = {key: _fold_in_str(rng, name) for key, rng in self.rngs.items()}
  File "/usr/local/lib/python3.8/dist-packages/flax/core/scope.py", line 459, in <dictcomp>
    rngs = {key: _fold_in_str(rng, name) for key, rng in self.rngs.items()}
  File "/usr/local/lib/python3.8/dist-packages/flax/core/scope.py", line 92, in _fold_in_str
    return random.fold_in(rng, jnp.uint32(hash_int))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/random.py", line 171, in fold_in
    return _return_prng_keys(wrapped, _fold_in(key, data))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/random.py", line 157, in _fold_in
    return key._fold_in(jnp.uint32(data))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/prng.py", line 185, in _fold_in
    return PRNGKeyArray(self.impl, self.impl.fold_in(self._keys, data))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/prng.py", line 448, in threefry_fold_in
    return _threefry_fold_in(key, jnp.uint32(data))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 424, in cache_miss
    out_flat = xla.xla_call(
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1661, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1652, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1664, in process
    return trace.process_call(self, fun, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 633, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 128, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 263, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 155, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars,
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 506, in compile
    self._executable = XlaCompiledComputation.from_xla_computation(
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 563, in from_xla_computation
    compiled = compile_or_get_cached(backend, xla_computation, options)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 534, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 514, in backend_compile
    return backend.compile(built_c, compile_options=options)
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: UNKNOWN: device kernel image is invalid
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_asm_compiler.cc(69): 'cuLinkComplete(link_state, &cubin_out, &cubin_size)'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workdisk/jax/FlaxExamples/flax/examples/imagenet/models_test.py", line 35, in test_resnet_v1_model
    variables = model_def.init(
  File "/workdisk/jax/FlaxExamples/flax/examples/imagenet/models.py", line 100, in __call__
    x = conv(self.num_filters, (7, 7), (2, 2),
  File "<string>", line 17, in __init__
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/random.py", line 171, in fold_in
    return _return_prng_keys(wrapped, _fold_in(key, data))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/random.py", line 157, in _fold_in
    return key._fold_in(jnp.uint32(data))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/prng.py", line 185, in _fold_in
    return PRNGKeyArray(self.impl, self.impl.fold_in(self._keys, data))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/prng.py", line 448, in threefry_fold_in
    return _threefry_fold_in(key, jnp.uint32(data))
RuntimeError: UNKNOWN: device kernel image is invalid
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_asm_compiler.cc(69): 'cuLinkComplete(link_state, &cubin_out, &cubin_size)'

----------------------------------------------------------------------
Ran 1 test in 1.762s

FAILED (errors=1)

Process finished with exit code 1
```

### Steps to reproduce:
Run command:
`/usr/bin/python3 -u /workdisk/jax/FlaxExamples/flax/examples/imagenet/models_test.py`

Tested with docker image: `nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04`
including the following installations:
  
  ```

  ENV PYTHON_VERSION=cp38 \
      CUDA_VERSION=cuda11 \
      PLATFORM=linux_x86_64 \
      BASE_URL='https://storage.googleapis.com/jax-releases'


  RUN set -ex; \
      pip install -U $BASE_URL/cuda11/jaxlib-0.1.75+cuda11.cudnn82-cp38-none-manylinux2010_x86_64.whl; \
      pip install -U jax \ 
      pip install --upgrade -q git+https://github.com/google/flax.git \
      pip install torchvision \
      pip install jupyter clu ml-collections 
       
       
       
  
  RUN pip install dm-tree dm-sonnet tensorflow tensorflow_datasets ipywidgets matplotlib dm-haiku
  RUN pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio===0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
  
  ```
PATH and LD_LIBRARY_PATH updated accordingly:
```
export PATH=/usr/local/cuda-11.3/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-11.3/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```

**Comment by marcvanzee** [comment] 2021-12-17 08:43
It seems your kernel image is invalid, which makes me suspect there is something wrong with your selected docker image `nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04`, perhaps it isn't supported by the XLA compiler, or perhaps there is a mismatch with jaxlib.

It would be useful if we can determine that this is independent of Flax, so you can file an issue against the JAX repo. It seems the error happens when using an RNG in a convolution. I can't easily reproduce your setup right now, but could you try running the following code on your machine and see whether you also get an error?

```python
from jax import lax, jit, random
import jax.numpy as jnp

def conv():
  lhs = jnp.ones((2, 3, 9, 10))
  rhs = random.normal(random.PRNGKey(0), ((3, 3, 4, 5)))
  return lax.conv_general_dilated(lhs, rhs, (1, 1), ((0,0), (0,0)))

jit(conv)()
```

**Comment by mattiasmar** [comment] 2021-12-17 08:54
That test ran successfully. the jit'ed conv returns a DeviceArray of dimensions (2, 3, 6, 6).

**Comment by marcvanzee** [comment] 2021-12-17 09:09
Hmm ok, on what machine are you running this and what GPU does it have?

**Comment by mattiasmar** [comment] 2021-12-17 09:15
I run it within a K8S environment, with a pod assigned with 40 CPU cores, 80Gi RAM and 8 GPU's (NVIDIA GeForce GTX TITAN X)

**Comment by marcvanzee** [comment] 2021-12-17 09:30
Ok, thanks for the details. Unfortunately I will be OOO for the coming two weeks so I can't help you further, but perhaps @jheek  can take a look at this next week since he should still be around.

**Comment by mattiasmar** [comment] 2022-01-10 20:31
If one
- uses the docker image `nvidia/cuda:11.4.1-cudnn8-devel-ubuntu18.04`, and 
- install jax by calling `pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html`, and 
- run the  flax test script [flax\examples\imagenet\models_test.py](flax\examples\imagenet\models_test.py) with `XLA_FLAGS=--xla_gpu_force_compilation_parallelism=1`

then the scripts completes with a success indicator.

**Comment by jheek** [comment] 2022-03-14 15:53
`XLA_FLAGS=--xla_gpu_force_compilation_parallelism=1`, so without this FLAG even the tests don't run?
If that's the case this bug should probably go into google/jax

**Comment by marcvanzee** [comment] 2022-04-27 20:42
@mattiasmar any updates?

**Comment by mattiasmar** [comment] 2022-04-28 18:09
Oh, since January I haven't got to try it out again. Probably the repo has changed a lot since then anyway.

**Comment by marcvanzee** [comment] 2022-04-28 18:54
Alright, I will close it for now then.

**Closed by marcvanzee** 2022-04-28 18:54 UTC
Labels: Priority: P1 - high
